backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "public/assets" 
public_folder: "/assets" 

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/contents" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/PostDetails.astro"}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Fecha de publicacion", name: "datetime", widget: "datetime"}
      - {label: "Mostrar en pantalla principal", name: "featured", widget: "boolean"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Contenido", name: "body", widget: "markdown"}
      